// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzqjtblwikvmutqxihgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6cWp0Ymx3aWt2bXV0cXhpaGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzY1MjksImV4cCI6MjA2NTU1MjUyOX0.J0os3Ht76W4N-GLCN9i8_wtWtkyHL4hfub7dx8Uc27c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);